# Generated by Django 3.0.6 on 2021-01-29 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fregistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=10)),
                ('Lname', models.CharField(max_length=10)),
                ('Mobile', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('State', models.CharField(max_length=15)),
                ('District', models.CharField(max_length=15)),
                ('Mandal', models.CharField(max_length=15)),
                ('Village', models.CharField(max_length=15)),
                ('Aadhaar', models.IntegerField()),
                ('Passbook', models.CharField(max_length=12)),
                ('Password', models.CharField(max_length=20)),
                ('Repassword', models.CharField(max_length=20)),
            ],
        ),
    ]
