# Generated by Django 3.0.6 on 2021-01-29 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pname', models.CharField(max_length=15)),
                ('Pprice', models.IntegerField()),
                ('Pdesc', models.TextField()),
                ('Pimage', models.ImageField(upload_to='images')),
            ],
        ),
    ]
