# Generated by Django 3.0.6 on 2021-01-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
